# Generated by Django 5.0.1 on 2024-01-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(max_length=80)),
                ('password', models.TextField(max_length=10)),
                ('verified', models.IntegerField(max_length=8)),
            ],
        ),
    ]
