# Generated by Django 5.0.1 on 2024-01-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_RPG_Creator', '0002_users_code_alter_users_password_alter_users_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='temp_password',
            field=models.TextField(default='00000000', max_length=8),
        ),
    ]
